### ISSUE TITLE
How to handle pivot table in rest?

### ISSUE THREAD

**Issue by vinaybedre** [diegohaz/rest#104]
Hi,
Assume I have 2 tables, Products and Orders and I would like to store the relationship in a third table Product_Order, which stores only Product ID and Order ID, how can this be achieved in rest?

**Comment by diegohaz** [comment]
If it doesn't make sense to have a third API for `Product_Order`, I would put it together with Products or Orders. And, depending on the complexity of the models, in the same model file. Which from both to choose is upon you.

Also, it's not called "tables" in the NoSQL world. It's "collections". And maybe you should research for a more NoSQL way to do that.
