### ISSUE TITLE
bcrypt npm install error

### ISSUE THREAD

**Issue by wrjanan** [diegohaz/rest#105]
I kept getting an issue with the "yo rest" command despite being a fresh install on my desktop.

After some searching, these 2 links helped to solve my issue and hopefully it will help you with your projects.

[Change npm version to 5.3.0](https://github.com/npm/npm/issues/18380)
[Change package.json bcrypt to     "bcrypt-nodejs": "*"](https://github.com/kelektiv/node.bcrypt.js/issues/432)

Hope this helps solve some of the issues unrelated to this lovely package!

Thanks diegohaz for your work on this restful api generators.

Now that I have gotten the bcrypt issue solved, it is play time with your package :)

**Comment by ompcse** [comment]
Install exact version. it will work
"bcrypt": "1.0.2"

**Comment by maustand** [comment]
Anyway if it is relevant. also you could use "bcrypt": "^1.0.3"... currently i am using this in my project and it works perfect.

Regards
