### ISSUE TITLE
Modify the information that shows when we consume the API of users

### ISSUE THREAD

**Issue by AlbertoIHP** [diegohaz/rest#108]
Hi !

I have been working with this generator to create a little app, i add some fields to de default user model, its looks like this

> const userSchema = new Schema({
  matricula:{
	type: String,
	required: true,
	unique: true
  },
	email: {
		type: String,
		match: /^\S+@\S+\.\S+$/,
		required: true,
		unique: true,
		trim: true,
		lowercase: true
	},
  lastname: {
	type: String,
	required: true,
  trim: true
  },
  profession:{
	type: String,
	required: true,
  trim: true
  },
	password: {
		type: String,
		required: true,
		minlength: 6
	},
	name: {
		type: String,
		index: true,
		trim: true,
	  required: true
	},
	services: {
		facebook: String
	},
	role: {
		type: String,
		enum: roles,
		default: 'user'
	},
	picture: {
		type: String,
		trim: true
	}
}, {
	timestamps: true
})

reading the code, i figured out that theres its a method that allows views fields of the model, so i have modified it to this

> userSchema.methods

 = {

	view (full) {
		let view =
    {
	   }
		let fields = ['id', 'name', 'picture']

		if (full) {
			fields = [...fields, 'lastname', 'profession', 'matricula', 'email', 'createdAt']
		}

		fields.forEach((field) => {
	  view[field] = this[field]
	})

		return view
	},

	authenticate (password) {
		return bcrypt.compare(password, this.password).then((valid) => valid ? this : false)
	}
}

As you can see, i add some new fields to be showed some user request my API, but i dont know why when i consume my API from my front the answer still being as no change was maded.

> createdAt

:
"2017-09-26T16:08:47.753Z"
email
:
"a.herrera07@ufromail.cl"
id
:
"59ca7b8f2cdec60d499c56f5"
name
:
"alberto"
picture
:
"https://gravatar.com/avatar/3332e24cd0b5dd858098056fc701a28b?d=identicon"

I hope you can help me, greetings (Sorry for my bad english)

**Comment by diegohaz** [comment]
Hi, @AlbertoIHP

You need to call `view(true)` on controller or just add those fields outside of `if (full) {}`.

**Comment by AlbertoIHP** [comment]
hi! thanks by your reply, i already did it but not change was done

**Comment by diegohaz** [comment]
Try to add some `console.log`s to ensure that `this[field]` exists.

**Comment by AlbertoIHP** [comment]
I actually did it before running dev script, and i create the front to add users with those filds that i add to the schema. And there is no problem, but when i try to update the información it only accept the name and the email to update evento when i modify the route to accept a body with those new filds. Besides that when i try to get some user información dont matter if i put all view calls un true, it still showing the createdat name id and email. I hace been trying to fix it al this day i check the code line by line. Help :(

**Comment by AlbertoIHP** [comment]
hi!! i restart my computer and i try again with 

> You need to call view(true) on controller or just add those fields outside of if (full) {}.

and this time it works, its seems to be that a thread of the service of api was listening at the 9000 port, even when i change it, was really wierd. but its fixed. thanks by your support !
