### ISSUE TITLE
Error Handling 

### ISSUE THREAD

**Issue by pantchox** [diegohaz/rest#109]
Hi,

In each entity endpoint index file, in `POST` method there is no use of `queryman`, it can be nice to add to the generator for each field you are creating if its mandatory so when user do `POST` for that entity `query` (queryman) is passed with the schema as well and if the required fields are not ok then message - same as queryman examples on the documentation.
Currently i can do `POST` with even empty fields and it will create the resource which is a bit not logical.

Maybe there is a different easy (or existing) way that i don't know of?

Another issue is that if i request a non existent endpoint with `POST`, it returns HTML with `"cannot POST"` and correct 404 status , how can i customize it? the `response\index.js` of not found is relevant only to existing routes.

Also adding header accepting JSON result does not return JSON error only that HTML, and for me as API its a big no no when the client expects JSON.

thanks!

Edit:
Another error is when i do `POST` with existing `id` , i receive html file with node stack error.
(to overcome this maybe add `.find` before creation if `id` is passed - which is not being passed - see this issue - https://github.com/diegohaz/rest/issues/110

**Comment by maustand** [comment]
Hi

If you need to valid your payload in a post method, you should use bodymen instead of querymen.

Something like :

```
// Index.js
import { middleware as body } from 'bodymen'
const { email, provider, pricing } = schema.tree


router.post('/',
  token({ required: true, roles: ['admin'] }),
  body({ 
    email: email,
    pricing: pricing,
    provider: { required: false, type: Object }, // use it in this way, instead of the schema property for complex objects.
  }),create)

```

Let me know if it works for you.

Regards
