### ISSUE TITLE
sending `id` in POST doesn't work

### ISSUE THREAD

**Issue by pantchox** [diegohaz/rest#110]
Hi,

When doing POST with the `id` it does not work, it is not being passed and saved to mongo, mongo generates its own.
I have used this code to generate valid ObjectId
```javascript
const ObjectId = (m = Math, d = Date, h = 16, s = s => m.floor(s).toString(h)) =>
    s(d.now() / 1000) + ' '.repeat(h).replace(/./g, () => s(m.random() * h))
```

from https://stackoverflow.com/questions/10593337/is-there-any-way-to-create-mongodb-like-id-strings-without-mongodb

In order to override it i had to update the Model Scehma (created from mongoose) of 
`{'_id: String}` and import it in the `index.js` file of the Entity/Resource.

like this
```javascript
router.post('/',
  ...
  body({ _id , ...})
  ...
```

but now it is mandatory to specify it.
I am doing this because my client generates the id.

Any ideas?

thanks.

**Comment by maustand** [comment]
have you tried  something like this ?

   Profiles: [{
    _id: false,
    myCustomID: {
      type: string,
      index: true
    },
    phone: {
      type: Number,
      required: true
    }
  }],

Regards !
