### ISSUE TITLE
[Question] Add sanitization to the generated api

### ISSUE THREAD

**Issue by yxliang01** [diegohaz/rest#111]
I feel like this generator should generate apis that do sanitize user inputs.

Thanks!

**Comment by maustand** [comment]
Hi @yxliang01 

In my production project that it was generated with this generator, we are using helmetjs.
it gives you a good middleware to avoid problems with the user inputs

Check this : https://github.com/helmetjs/helmet


Anyway i think that it would be great to add a middleware like this to avoid malicious user inputs.

@diegohaz what do you think about it ?
If you consider, i could add this feature and give the option in the generator to use helmetjs.

let me know !

**Comment by yxliang01** [comment]
Hey @maustand ! helmetjs looks good! I would say your suggestion to add helmetjs to this generator is favourable. 

Thanks!

**Comment by maustand** [comment]
No pro broskie !.

Just you should add it on express/index.js, beside of the forceSSL middle ware


```
    /* istanbul ignore next */
    if (env === 'production' ) {

        /* Use Helmet */
        app.use(helmet());

        /*Force SSL */
        app.set('forceSSLOptions', {
            enable301Redirects: true,
            trustXFPHeader: true,
            httpsPort: 443,
            sslRequiredMessage: 'SSL Required.'
        });

        app.use(forceSSL);
    }
```

**Comment by diegohaz** [comment]
@maustand Sure. I think it would be great. No need to give an option on the generator.
