### ISSUE TITLE
How To query a search?

### ISSUE THREAD

**Issue by schmanat** [diegohaz/rest#125]
Hi, first of all thanks for this generator. 

I have a (stupid) question. I set up an entity with the two fields (strbez, strnr). No I would like to implement a search. I saw its possible with the q parmater.
Can somebody give me the right hint how the query should look like.

In example:
I would like to search for the term 'Altweg' (strbez). I try to query it this way:

localhost:9000/streets?q=altweg&fields=strbez. I get allways an empty response (Code 200).

**Comment by diegohaz** [comment]
`fields` defines the fields you want to be returned in response. In that case, it will only return `strbez`, and not `strnr`.

`q` does a regex search on a `keywords` field.

You can either configure it to search on another field on the route definition (`/src/api/api-name/index.js`), like this:
```js
query({ q: { paths: ['strnr'] } })
```

Or use https://github.com/diegohaz/mongoose-keywords to create a `keywords` field based on `strnr`:

On model:
```js
MySchema.plugin(require('mongoose-keywords'), {paths: ['strnr']})
```

**Comment by schmanat** [comment]
Thx for your quick replay. I have now installed the mongoose-keywords plugin and add it to my model. 

    streetsSchema.plugin(require('mongoose-keywords'), {paths: ['strbez', 'strnr']});

If I try the q parameter (/streets?q=altweg) I see in the console the query. 

    streetsSchema.plugin(require('mongoose-keywords'), {paths: ['strbez', 'strnr']});

But the result is emtpy, same behavior as before. Have I add the keyword field also to my schema?

**Comment by schmanat** [comment]
Now I could solve the issue. @diegohaz  thanks for your help.
The problem was, that I forget to configure the model the right way.
Who can read is clearly in the advantage 😄

**Comment by UrbanSwati** [comment]
Hey, can you make an example of the q (regex) query?

For example, I have projects for each user, so I want to get only projects of a certain user by using the user id that is automatically created
