### ISSUE TITLE
Can you default the database to MySQL or have an option to choose mongoDB or MySQL?

### ISSUE THREAD

**Issue by mpraki** [diegohaz/rest#126]
Not all people use mongoDB, if you have an option to create the project for one of the relational database like MySQL, it will be helpful for lot of people.

**Comment by maustand** [comment]
Hi

Probably it would be a nice feature to have..  but  the main focus of this generator, it is the MEN stack ( Mongo, Express and Nodejs ).

Let's see if there is someone who has open source stamina for it ! =)

Anyway PR are always welcome !

Regards

**Comment by diegohaz** [comment]
I'm closing this for now. If anyone wants to work on this I can reopen it.
