### ISSUE TITLE
VS Code debug

### ISSUE THREAD

**Issue by marcus2vinicius** [diegohaz/rest#127]
Hello guys, how to debug using vs code ?

Thank you

**Comment by marcus2vinicius** [comment]
I tried this tutorial https://github.com/bdspen/nodemon_vscode and added in package.json `--debug `.
Result:
`"dev": "nodemon --debug -i \"*.test.js\" .",`

But is not works

**Comment by maustand** [comment]
Hi

Honestly i dont know how to debug in vs code.
Anyway this is not related to the rest:generator.
In other hand, if you are looking for how you could integrate and use the pre defined task with your env, as marcus tell you, try to review the package.json and see the pre defined task that the generator has.

Also if you need know how you can debug in nodejs, i advice you to read [this article](https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27) 

Regards !
