### ISSUE TITLE
yo rest:api -> Which fields the model will have? Not "id".

### ISSUE THREAD

**Issue by NNTin** [diegohaz/rest#128]
When I add a new API via `yo rest:api` it will eventually ask me `which fields the model will have (comma separated)`.  
I did the mistake of calling one of the fields `id`. As a result when I am testing the API with Postman it won't allow me to get an individual entry, modify the entry or delete the entry.

Getting all entries, creating users and so on worked fine. I've been struggling for hours because of this bug and finally located it.

**Comment by diegohaz** [comment]
Hi, @NNTin 

Maybe we should add a note on the question (something like `(comma separated, do not include id)`).

Could you send a PR?
