### ISSUE TITLE
Whats the right place to ask general Questions

### ISSUE THREAD

**Issue by schmanat** [diegohaz/rest#130]
Sorry for that issue, but whats the right place to aks general questions?

For example, I would like to know if its possible to query (q=) a set of data depending on the updateAt field. Is that out of the box possible or I have to implement this on my own?

**Comment by maustand** [comment]
I think that it is out of the box and you should create your own middleware for deal with it.

you could send your data via queryString. using queryman and after this, you could create a middleware that it modifies the querystring that u are geting, depending your criteria or in this case, depending updateAt.

In other had, you could review the querymen documentation.. just in case 
https://github.com/diegohaz/querymen

Anyway it would be something like : 


```
// index.js

router.get('/',
  token({ required: true  }),
  query(),
  conditionalQuery()
  index)

```
`
//middleware/conditionalQuery

export const conditionalQuery = ({ querymen: { query, select, cursor } }, res, next) =>

   if(isOldDay(query.updateAt)) {
      // do special querymen
        req.conditionalQueryMen = {
        userSpecialCondition: 'Foo',
        }
    }
  next();
};


`





Regards

**Comment by schmanat** [comment]
great thx for your answer.
