### ISSUE TITLE
Unhandled Error when begin to generate 

### ISSUE THREAD

**Issue by MetCoder95** [diegohaz/rest#133]
When I start to generate, after completing the form, I have this issue:

```
events.js:193
      throw er; // Unhandled 'error' event
      ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at randomBytes (internal/crypto/random.js:44:11)
    at Object.options.source (/home/metcoder/.nvm/versions/node/v9.0.0/lib/node_modules/generator-rest/node_modules/rand-token/index.js:61:18)
    at Object.generate (/home/metcoder/.nvm/versions/node/v9.0.0/lib/node_modules/generator-rest/node_modules/rand-token/index.js:96:29)
    at /home/metcoder/.nvm/versions/node/v9.0.0/lib/node_modules/generator-rest/generators/app/index.js:98:40
    at <anonymous>
 ```

I updated the package and yeoman and continue with this problem.

**Comment by maustand** [comment]
HI
Probably there is a unexpected error with the last merge , where we updated  crypto to the last version for support nodejs 9.

anyway let me check in this weekend and see what it is happening !

Probably it is referenced to [this bug ](https://github.com/nodejs/node/issues/16778)

**Comment by Ikramhassan** [comment]
I am facing the same problem. When i select Yes for the following question I get this error.
? Do you want the retrieve methods from users (GET) to have the form { rows, co
unt } ? Yes
events.js:136
      throw er; // Unhandled 'error' event
      ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at randomBytes (internal/crypto/random.js:44:11)
    at Object.options.source (C:\Users\ikram\AppData\Roaming\npm\node_modules\generator-rest\node_modules\rand-token\index.js:61:18)
    at Object.generate (C:\Users\ikram\AppData\Roaming\npm\node_modules\generator-rest\node_modules\rand-token\index.js:96:29)
    at C:\Users\ikram\AppData\Roaming\npm\node_modules\generator-rest\generators\app\index.js:98:40
    at <anonymous>

**Comment by maustand** [comment]
@Ikramhassan  could you let me know what nodejs version do you have in your env ?

**Comment by Ikramhassan** [comment]
v9.2.0.

**Comment by maustand** [comment]
@diegohaz Hi diego, could you make a deploy ?

This bug is related to [this pull request ](https://github.com/diegohaz/rest/pull/131)that it resolves the problem..

@Ikramhassan  if you dont want to wait for the deploy, just you should update the last version of crypto in your local env and it should work.

Regards

**Comment by diegohaz** [comment]
Sure. Publishing new version right now.

**Comment by diegohaz** [comment]
`v0.11.1` released
