### ISSUE TITLE
How to handle file upload

### ISSUE THREAD

**Issue by hriverahdez** [diegohaz/rest#134]
I'm new to nodejs and express but I've googled around and according to what I've seen it is very common to use file uploading libraries like Formidable. I've seen examples and they're simple, however I wonder if it's necessary to add another library for this purpose. Does the generator allow in some way to gain access to the file sent in the request by default? If not I would appreciate some insight on what would be the best way to include said library (or any other) into the generator's existing structure. Perhaps it's me failing to understand something or my lack of knowledge in node, but I see that you're using the bodymen middleware to parse the body for the api endpoints so you don't access the req object directly, and you also specify the schema for that body in the index of that endpoint so I don't know how to include a file in this setup. Thanks. 

P.S: BTW like the generator a lot keep up the good work!

**Comment by rajatady** [comment]
Hey @hriverahdez ,

You can upload files using the multer package.
[https://github.com/expressjs/multer](https://github.com/expressjs/multer)

Multer provides the middleware for uploading files to the specified storage engine.
I recently integrated multer with the rest-generator for a project and its pretty easy.

```javascript
import multer from 'multer'
import path from 'path'
import _ from 'lodash'
 ...
 ...
const storage = multer.diskStorage({
  destination: function (req, file, callback) {
    callback(null, path.resolve('./uploads'))
  },
  filename: function (req, file, callback) {
    var name = file.originalname.split('.')[0] + '-' + Date.now() + path.extname(file.originalname)
    name = _.replace(name, /\s/g, '_')
    callback(null, name)
  }
})
const upload = multer({storage: storage})

...
...
...
/**
 * @api {post} /images Create images
 * @apiName CreateImages
 * @apiGroup Images
 * @apiPermission user
 * @apiParam {String} access_token user access token.
 * @apiSuccess {Object} images Images's data.
 * @apiError {Object} 400 Some parameters may contain invalid values.
 * @apiError 404 Images not found.
 * @apiError 401 user access only.
 */
router.post('/',
  token({required: true}),
  upload.single('image'),
  create)
...
...
```

If the image upload by multer is successful, the create method will get the file as a property of the req object, req.file in case of single upload and req.files in case of array upload. You can save the file data in the database like so.

```javascript
export const create = ({ user, file }, res, next) =>
  Images.create({ ...file, createdBy: user })
    .then((images) => images.view(true))
    .then(success(res, 201))
    .catch(next)
```

Hope this helps.

**Comment by maustand** [comment]
@rajatady thanks !

**Comment by hriverahdez** [comment]
@rajatady Wow! It is pretty easy. Thanks a lot, this is exactly what I needed
