### ISSUE TITLE
Logout functionality, session handling

### ISSUE THREAD

**Issue by divanvb** [diegohaz/rest#136]
Good day

I want to know how the sessions are handled by the server. Tried implementing a logout function on the front end by just removing the token stored within my ionic application but the security company I use states that they could still make requests with the session token. How can I remove the session or reset it so that this isn't possible?

**Comment by diegohaz** [comment]
Server only verifies if the JWT token is valid, which means that it was signed with correct secret.

You can change the secret, but it would invalidate all tokens from all clients.

You can find other options here: https://stackoverflow.com/a/23089839/5513909
