### ISSUE TITLE
Authentication check

### ISSUE THREAD

**Issue by divanvb** [diegohaz/rest#138]
Hi

Where in the code is the token being checked for being valid as I want to implement a key blacklist from your previous SO suggestion but I can't seem to find where it authenticates so that I can check if the token is in the blacklist table when "logging out" on the server side.

**Comment by maustand** [comment]
Hi.

I think that if you want to implement a blacklist, you should do it in the next code line: 


```
// servfices/passport.
passport.use('token', new JwtStrategy({
  secretOrKey: jwtSecret,
  jwtFromRequest: ExtractJwt.fromExtractors([
    ExtractJwt.fromUrlQueryParameter('access_token'),
    ExtractJwt.fromBodyField('access_token'),
    ExtractJwt.fromAuthHeaderWithScheme('Bearer')
  ])
}, ({ id }, done) => {
  User.findById(id).then((user) => {

///// here..
    done(null, user);
    return null;
  }).catch(done);
}));
```


also you could check services/jwt.
Regards

**Comment by divanvb** [comment]
I've tried it there but for some reason, even placing a breakpoint there doesn't seem to have any effect. Maybe is just my environment but will still have a look thanks. JWT was the first place I checked but no luck there.

**Comment by divanvb** [comment]
@maustand Within that function you suggested, how can I access the actual token?

**Comment by maustand** [comment]
You could try to use some of the extractors to get the token and after this, you could do your own logic for check if the token is on blacklist.

In General, the generator just creates a token and verify it... there is not more logic or something else that  generator does..

I suggest you to read about passport and JWT documentation to understand how it works..

In other hand you could check the flow inside the services/passport folder. Basically you  could see the next lines where it is declared that passport will use a handler function called "token" and gives it a middleware handler that it will be called , in case "token" performed all the required verification without problems.
After this, this middleware will find an user for passing it into the declarations of the endpoint ( api ).

```
export const token = ({ required, roles = User.roles } = {}) => (req, res, next) =>
  passport.authenticate('token', { session: false }, (err, user, info) => {
    if (err || (required && !user) || (required && !~roles.indexOf(user.role))) {
      return res.status(401).end();
    }
    req.logIn(user, { session: false }, (err) => {
      if (err) return res.status(401).end();
      next();
    });
  })(req, res, next);



passport.use('token', new JwtStrategy({
........
}, ({ id }, done) => {
  User.findById(id).then((user) => {
    done(null, user);
    return null;
  }).catch(done);
}));

```
Regards
