### ISSUE TITLE
After running in dev, trying to post /users results in "Can't post users"

### ISSUE THREAD

**Issue by wenduzer** [diegohaz/rest#141]
tried 4 times to re-install and create new projects,
everytime I try to post using postman, I get "cannot post /users" and I even followed the videp step by step without heroku, in dev mode.

**Comment by Souhail136** [comment]
Hello,
did you add the prefix 'api' in your URL ? just like http://localhost:9000/api/users

**Comment by maustand** [comment]
@wenduzer DId you resolve your problem ? as Souhail told you, just you should check your /api/index.js and see the defintion of your entrypoint.

Let me know if you was able to resolve your problem for closing this thread

**Comment by wenduzer** [comment]
Yeah it's my bad, in the video he wasn't using /api so I didn't tried that. Thanks, works great!

**Comment by wenduzer** [comment]
Yeah it's my bad, in the video he wasn't using /api so I didn't tried that. Thanks, works great!

**Comment by wenduzer** [comment]
Yeah it's my bad, in the video he wasn't using /api so I didn't tried that. Thanks, works great!

**Comment by wenduzer** [comment]
Yeah it's my bad, in the video he wasn't using /api so I didn't tried that. Thanks, works great!

**Comment by wenduzer** [comment]
Yeah it's my bad, in the video he wasn't using /api so I didn't tried that. Thanks, works great!

**Comment by wenduzer** [comment]
Yeah it's my bad, in the video he wasn't using /api so I didn't tried that. Thanks, works great!

**Comment by wenduzer** [comment]
Yeah it's my bad, in the video he wasn't using /api so I didn't tried that. Thanks, works great!

**Comment by wenduzer** [comment]
Yeah it's my bad, in the video he wasn't using /api so I didn't tried that. Thanks, works great!

**Comment by wenduzer** [comment]
Yeah it's my bad, in the video he wasn't using /api so I didn't tried that. Thanks, works great!

**Comment by maustand** [comment]
Great.
