### ISSUE TITLE
If i lost my master key, can i get other?

### ISSUE THREAD

**Issue by jorgeluisrezende** [diegohaz/rest#144]
i have this question, the .env should be keeped secure, but if i install other os and forget to save the .env? there's a way to get other master key?

**Comment by diegohaz** [comment]
Yes, @jorgeluisrezende. You just need to create another .env file with a new key.

**Comment by jorgeluisrezende** [comment]
Can i use any hash key?

**Comment by diegohaz** [comment]
You can use any set of characters (it can be a word, for example).
