### ISSUE TITLE
Didn't found the right place to post it, please don't kill me!

### ISSUE THREAD

**Issue by onluiz** [diegohaz/rest#145]
Hi!
I did not found another place to post it, so I'm sorry if this is the wrong local fo such question.

I started using this rest generator and with out a doubt I can say this is awesome! (Seriously, it is saving my life).

My question is: this project is still receiving conttribution? If so, I would like do contributte somehow (with docs or testing, ou issues, or anything you need).

Anyway... thank you all for the good job!

**Comment by jonathan-stone** [comment]
https://github.com/diegohaz/rest/commits/master

**Comment by jlmonteagudo** [comment]
Hello, I agree with onluiz.

I think that this project is awesome and it's a pity that it was discontinued.

If Diego confirms that it's discontinued then it would be nice to know it, so we could fork it and develop it on our own.

Thank you for this great project!

**Comment by diegohaz** [comment]
The project isn't discontinued, guys.

Contributions are very welcome.
