### ISSUE TITLE
Duplicate declaration body

### ISSUE THREAD

**Issue by flzpenteado** [diegohaz/rest#146]
I'm receiving this error when i try to run npm start
`TypeError: C:/estudo/node/simple-post-api/src/api/post/index.js: Duplicate declaration "body"`

`const router = new Router()
 const { title, body } = schema.tree
                     ^
`

**Comment by diegohaz** [comment]
That's not related to `bodymen`. You probably have already declared `body` in your file.

**Comment by flzpenteado** [comment]
My mistake!...Thanks!!!
