### ISSUE TITLE
import { Xobject } from '.' in a controller loads Xobject === undefined

### ISSUE THREAD

**Issue by Claus1** [diegohaz/rest#147]
Hi! I am new in Nodejs and Moongose. I found that in a generated controller   
`import { Xobject } from '.'`
 does not work for me, that causes later  a error like Cannot read property 'find' of undefined (from Xobject)

As I undestood  '.' means index.js in the same directory that exports the router only. A attempt to import 
Xobject from appropriated model.js file did not help although it contains in the their deep objects Xobject property. Can someone explain me how do force it to work and where is a error?

**Comment by onluiz** [comment]
Try `import { Xobject } from **'./'**`

It should get the index.js of yours.

By the way, how are you exporting your `find` function?

Hope I can help =)

**Comment by Claus1** [comment]
Hi! The generated code has to exports a model file but it seems does it wrong. Xobject is undefined after exporting.

**Comment by maustand** [comment]
@claus1 did you get a solution or still not ?

Regards :)

**Comment by Claus1** [comment]
Hi! I switched to use another template and did not check it. Sorry for that :)
