### ISSUE TITLE
Mongo URI error

### ISSUE THREAD

**Issue by jorgeluisrezende** [diegohaz/rest#149]
Hey Dieago, could you help me ?
i can not to connect in the database in production mode, my mongodb is installed at amazon ec2, but i'm getting an authentication error from db....

**Comment by maustand** [comment]
Hi.

Have you tried to check your config.js file ? in the main folder  ?
Probably you have a problem with credentials...

The generator is agnostic to the cloub.

**Comment by jorgeluisrezende** [comment]
yeah, i had verified the credentials etc, its all right...

**Comment by maustand** [comment]
Honestly i dont think that there would be a problem with the generator and ec2.

The generator is agnostic. Probably you have a problem related to networking or credentials....

 Only you should set your right credentials in your config file, keeping in mind the environment and task that you want to run in your server ( credentials for prod, test, bla ).

Have you tried to connect your mongodb instance on amazon with your local machine ?, for example, using shell or robomongo to connect your pc and the mongo instance in the cloub ?

**Comment by the-vladman** [comment]
you add `.env` File?
It's neccesary

**Comment by jorgeluisrezende** [comment]
i did it works, thank you guys for comment.
