### ISSUE TITLE
How to query a search?

### ISSUE THREAD

**Issue by UrbanSwati** [diegohaz/rest#150]
Hey, can you make an example on how to use the q (regex) query?

**Comment by maustand** [comment]
Hi @UrbanSwati 

Could you clarify what regex are you meaning ?

do you mean about [querymen](https://github.com/diegohaz/querymen) ? 

In this case, you should check the documentation of this plugin.

Let me know if you have a problem.

**Comment by UrbanSwati** [comment]
![screen shot 2018-03-05 at 8 32 25 am](https://user-images.githubusercontent.com/30931804/36960552-2de25982-2050-11e8-8eca-630a5a4c2c1f.png)

Can you make an example of this
