### ISSUE TITLE
Running in production mode using pm2 or forever

### ISSUE THREAD

**Issue by axcl** [diegohaz/rest#153]
Hi,

Is there any way of running the application using pm2 or forever

**Comment by maustand** [comment]
Hi @axcl 

Honestly i dont know anything about pm2 but i think that it should not be a problem because generators creates an normal Node.js/express app at the end...
So there would not be any troubles.

anyway @diegohaz  do you have something to say ?

Regards

**Comment by axcl** [comment]
Hi Thanks, it worked using babel-node interpreter with pm2.

Exact command is

pm2 start src/app.js --interpreter=babel-node

**Comment by jorgeluisrezende** [comment]
@axcl I am using pm2 with generator rest, and i just use "pm2 start ." and it works perfectly

**Comment by maustand** [comment]
Good info :+1:
