### ISSUE TITLE
JWT auth error - token function passing null to id 

### ISSUE THREAD

**Issue by jorgeluisrezende** [diegohaz/rest#155]
I'm getting an error with jwt auth, i dont know why but the `token()` is passing null to id parameter, it was started yesterday...

the message log: 
"Mongoose: users.findOne({ _id: null }, { fields: {} })"

**Comment by maustand** [comment]
Hi.

Did you check that token middle ware is working  right ?

Could you give us more details ?

**Comment by jorgeluisrezende** [comment]
Hi, thank you for try help me, that error was because i made mistake when i sigin the JWT, i got to fix it
