### ISSUE TITLE
apiRoot should be / by default

### ISSUE THREAD

**Issue by diegohaz** [diegohaz/rest#157]
Since v0.11.0 we have a prefix path for APIs (#87). We didn't update the docs though, which are leading to some confusion, such as #156 and others.

Instead of updating docs, I'd prefer that we restore it to be `/` by default.

Updating this line should do the job: https://github.com/diegohaz/rest/blob/master/generators/app/templates/src/config.js#L27

**Comment by maustand** [comment]
@diegohaz I think that it should be as you say..
Setting a prefix for the API, it shoud be added for the user ( developer )..

In my project, i did it.. but it should not be defiend by defualt for our generator..
