### ISSUE TITLE
Support for model relations

### ISSUE THREAD

**Issue by habbes** [diegohaz/rest#16]
Hey. Could support for model relations be added, so we could be able to use the generator to have endpoints like `GET books/{id}/pages`?

**Comment by diegohaz** [comment]
Assuming you have generated a `page` and a `book` APIs, it can be done easily by updating few lines on the book api:

1. Add `/:id/:resource` route to **book.router.js**:
```js
router.get('/:id/:resource',
  show)
```

2. Update the `show` method in **book.controller.js**
```js
export const show = ({ params }, res, next) =>
  Book.findById(params.id)
    .populate(params.resource)
    .then(notFound(res))
    .then((entity) => book ? book.view()[resource] : null)
    .then(success(res))
    .catch(next)
```

3. Add reference in **book.model.js**
```js
const bookSchema = new Schema({
  pages: [{
    type: Schema.ObjectId,
    ref: 'Page'
  }]
}, {
  timestamps: true
})

bookSchema.methods = {
  view () {
    const view = {
      // simple view
      id: this.id,
      pages: this.pages ? this.pages.view() : undefined,
      createdAt: this.createdAt,
      updatedAt: this.updatedAt
    }
    return view
  }
}
```

I didn't test this code, but it should work. It can be optimized though. 

Also, It would be nice if we could do this with the generator. I just need more use cases. I would be grateful if you share your code (or a snippet) when you finish. :)

**Comment by habbes** [comment]
Okay thanks... I will when I do.

But that will work just for embedding a page in a book response, it won't create extra routes, for instance creating a new page on a related book, `POST /books/{bookId}/pages`?

**Comment by diegohaz** [comment]
In an easy way, you can reimplement the logic from `POST /pages` to the books API.

**Comment by habbes** [comment]
Okay, I will try that. Thanks for the prompt response.

**Comment by aaronksaunders** [comment]
can you provide an example of what the Page Schema looks like to complete the example?

**Comment by diegohaz** [comment]
@aaronksaunders It should work with a simple one generated with `yo rest:api`

**Comment by aaronksaunders** [comment]
i guess i am confused with how the relationship is saved since there is not an example of POST for the 

> In an easy way, you can reimplement the logic from POST /pages to the books API.

not sure what exactly this means?

**Comment by diegohaz** [comment]
Hi, @aaronksaunders 

If you generate an API with `yo rest:api` it will create something like:

**page.router.js**
```js
// grabs schema fields from the model
const { title, content } = schema.tree

// enables the route POST /pages
router.post('/',
  body({ title, content }),
  create)
```

**page.controller.js**
```js
export const create = ({ bodymen: { body } }, res, next) =>
  Page.create(body)
    .then((page) => page.view(true))
    .then(success(res, 201))
    .catch(next)
```

And this is the logic behind `POST /pages`.

To implement this on `POST /books/:id/pages`, you need to make something like:

**book.router.js**
```js
import { schema as pageSchema } from '../page'
// grabs schema fields from the page model
const { title, content } = pageSchema.tree

// enables the route POST /books/:id/pages
router.post('/:id/pages',
  body({ title, content }),
  createPage)
```

**book.controller.js**
```js
import { Page } from '../page'
 
export const createPage = ({ params, bodymen: { body } }, res, next) =>
  Book.findById(params.id)
    .then(notFound(res))
    .then((book) => {
      if (!book) return null // book wasn't found
      // create page from request body
      return Page.create(body).then((page) => {
        // add page to book.pages
        book.pages.addToSet(page)
        return book.save()
      })
    })
    .then((book) => book ? book.view(true).pages : null)
    .then(success(res, 201))
    .catch(next)
```

It should be enough. I wrote this directly on GitHub, then it may contain some errors.

We can improve this code and add this to the generator, but I want to see how the people use this, because I usually don't make requests this way (I would first create the page `POST /pages` and then update the book `PUT /books`).

If you want to learn more about the code, please refer to this repo: https://github.com/diegohaz/generator-rest-example
It has the generated code with some comments.

**Comment by eliascalabrese** [comment]
Hi, I'm trying a similar action like add a comment to post where I´ve  comments:[] . 
POST /posts/:id/comment  this endpoint will push the comment reference to the post but I can't make it works.

thanks !
