### ISSUE TITLE
What's the point of the MasterKey?

### ISSUE THREAD

**Issue by nlucero** [diegohaz/rest#168]
First of all, excellent work here. This generator looks really good.

I'm having trouble wrapping my head around the concept of the _MasterKey_. What's its purpose, exactly? Is it some sort of API key? I think this should be mentioned in the documentation.

**Comment by cesar3030** [comment]
Hey @nlucero!  
I had trouble to understand the goal of the _masterKey_ when I started using this generator so I looked into the issues and this is what I found: issue #67 
I hope it will help!

**Comment by nlucero** [comment]
Hey! Thanks for the link. I used the search before creating this issue but for some reason I didn't find that one.

Anyways, I see what's the point of the master key now. Not sure if it's the best approach for the problem but it's a valid one for sure.
