### ISSUE TITLE
Options are not merged properly

### ISSUE THREAD

**Issue by kbzowski** [diegohaz/rest#169]
Object.assign (which is used for merging configs) allows only for shallow merges. As a result mongo options defined in "all" are ignored.

The issue can be easily shown by adding 
`console.log(config.all.mongo.options)`
after 
`module.exports = Object.assign(config.all, config[config.all.env])`

**Comment by diegohaz** [comment]
Hey, thank you for reporting it. Do you mind sending a PR with a fix? Probably using lodash's merge should do the job.
