### ISSUE TITLE
Query is limiting with 30 elements when i fetch a GET to my endpoint

### ISSUE THREAD

**Issue by AlbertoIHP** [diegohaz/rest#184]
I figured out on my console that it was limiting the fetch

` myDoc.find({}, { skip: 0, limit: 30, sort: { createdAt: -1 }, fields: {} })`

this is kind of wierd, if i could modify it i will post it here.

If there are someone else that already live this, please help us.

Greetings.

**Comment by DanMMX** [comment]
This is because of the default limit on [querymen](https://github.com/diegohaz/querymen).

You can find more info [here](https://github.com/diegohaz/querymen/issues/64)

**Comment by AlbertoIHP** [comment]
I figured out that is because of this https://github.com/diegohaz/querymen 
An amazing feature for handling the queries from frontend.



Diego you are amazing dude !! :)
