### ISSUE TITLE
Deprecated Stuff

### ISSUE THREAD

**Issue by Exlord** [diegohaz/rest#197]
DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.

DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
https://github.com/Automattic/mongoose/issues/6890#issuecomment-416218953

**Comment by webdelin** [comment]
mongoose.connect(keys.mongoURI, {
    useCreateIndex: true,
    useNewUrlParser: true
})
Node -> 
[nodemon] restarting due to changes...
[nodemon] starting `node index index.js`
Server Started on 5000
MongoDB Connected

**Comment by tinevra17** [comment]
@webdelin where is the file that I need to change to fix this issue?
