### ISSUE TITLE
Missing actions and documentations when using auth

### ISSUE THREAD

**Issue by Exlord** [diegohaz/rest#198]
How to register user from a registration page? (not using master key!)
how to Singin(auth) with username/password??

**Update :** 
-
ok found out how to login with basic auth, but it just returns unauthurized, unless I remove the `master()` handler from the auth route ...

```
router.post('/',
  master(),
  password(),
  login);
```

only can login in with Basic Auth if I remove the ` master(),`;

**Comment by diegohaz** [comment]
Hi @Exlord. If you want to sign in without the master key, you should remove `master()`. Otherwise you need to provide the master key.
