### ISSUE TITLE
Can querymen automatically handle lowercase vs uppercase searches

### ISSUE THREAD

**Issue by jaredgib** [diegohaz/rest#232]
I have one entry like this 

{"english": "Exact count-per-interval interobserver agreement (IOA)"}

when i query for ?english=exact 

i get 0 return from postman

when i query for ?english=Exact

i get the correct response. 

Is there a way to tell querymen, 'dont worry about lowercase vs uppercase'? 

how can we force querymen to ignore this?

**Comment by diegohaz** [comment]
Try to pass `normalize: true` to the field properties in `query()`.

**Comment by diegohaz** [comment]
`type: RegExp` should solve this as well.

**Comment by jaredgib** [comment]
thank you! trying this now!

<img width="219" alt="Screen Shot 2020-06-16 at 4 50 18 PM" src="https://user-images.githubusercontent.com/58823942/84826795-81548300-aff1-11ea-9790-68cfa7944b74.png">

**Comment by diegohaz** [comment]
Cool! I guess you don't need `operator: '$regex'` as `type: RegExp` will already handle it.
