### ISSUE TITLE
same issue

### ISSUE THREAD

**Issue by RENJITHVS** [diegohaz/rest#250]
remote: -----> Building on the Heroku-20 stack
remote:  !     No default language could be detected for this app.
remote:                         HINT: This occurs when Heroku cannot detect the buildpack to use for this application automatically.
remote:                         See https://devcenter.heroku.com/articles/buildpacks
remote:
remote:  !     Push failed

**Comment by Angelk90** [comment]
@RENJITHVS : Were you able to upload the project to heroku?
I still don't find a solution.

**Comment by RENJITHVS** [comment]
yes ,I can able to upload my project to Heroku from Windows , I  have done these steps


- Go to 'Getting Started on Heroku with Python'
- Create a Heroku account
- install pipenv
- Install git ( check git --version)
- Install Heroku CLI
- Login heroku
- Create a virtual environment
- Run manage.py not gonna run - pip freeze nothing installing
- Check which version django, requests you have and install it
- Run manage.py and then stop it
- Go to Django Heroku
- Create a Procfile and 
- Install django-heroku
- Add stuff to settings.py file
- Install guincorn (u can't run  it on windows! No problem move on..!)
- pip freeze - requirements.txt (use the angle bracket after pip freeze. Youtube doesn't allow angle bracket in description :/ )
- heroku create <appname> (to create an app on heroku)
- git status git commands - (git push heroku master)
- Open up the website)
- Admin panel not working. Heroku run bash. Migrations

Host your website completely free here. Have Fun!
