### ISSUE TITLE
Thoughts on GraphQL

### ISSUE THREAD

**Issue by diegohaz** [diegohaz/rest#40]
Some people are asking me about GraphQL support. I don't have much experience with it. But, as far as I know (please, correct me if I'm wrong), REST and GraphQL are two different approaches and can not coexist.

I'm working on some projects that would benefit from a GraphQL API, so I'm very into learning it and perhaps creating/using another generator or integrating it on `generator-rest` (if it's possible).

Just creating this thread to see if there're more people interested on this.

cc @cameronroe @arraisgabriel

**Comment by cameronroe** [comment]
GraphQL is merely a proxy that can sit over one or many REST APIs to resolve data. For example you could use a mongo database directly with a GraphQL connector or resolve a REST call. It's merely an interface to expose the data through queries. Nice.

Here's a starter course:
- https://learngraphql.com/basics/introduction

Here's also a great tutorial on using multiple datastores:
- https://www.youtube.com/watch?v=PHabPhgRUuU

Ready to kick things off if you guys are!

**Comment by diegohaz** [comment]
> For example you could use a mongo database directly with a GraphQL connector or resolve a REST call
It makes sense. I'll take a look at those resources.
