### ISSUE TITLE
Override limit 100

### ISSUE THREAD

**Issue by timothystewart6** [diegohaz/rest#56]
What's the easiest way to override the limit of 100 for an api?  I think this is coming form your other lib `querymen` but I am not really sure how to override it.  It looks like maybe I can do this in the router, or the model, or?

When I try to set a limit greater than 100 I get:

logs?limit=101
```
{
  "name": "max",
  "param": "limit",
  "value": 101,
  "max": 100,
  "valid": false,
  "message": "limit must be lower than or equal to 100"
}
```

**Comment by diegohaz** [comment]
You can do that in router:

```js
router.get('/', query({ limit: { max: 500 } }), index)
```

**Comment by timothystewart6** [comment]
Thank you so much!

**Comment by bookkcokr** [comment]
don't work within 
```js
const schema = new QuerymenSchema({
...
limit: { max: 500 },
...
})
router.get('/', query(schema), index)
```

what should i do???

**Comment by DanMMX** [comment]
don't use query schema, it might be related to [this](https://github.com/diegohaz/querymen/issues/50)
