### ISSUE TITLE
Building the Project

### ISSUE THREAD

**Issue by jenasubodh** [diegohaz/rest#60]
"npm run build" - Command not present. Can you please add it.

**Comment by diegohaz** [comment]
Hey, @jenasubodh 

It was removed in `v0.8.0` (release notes: https://github.com/diegohaz/rest/releases/tag/v0.8.0)

Just deploy the root directory.

**Comment by jenasubodh** [comment]
Hey @diegohaz thanks for your quick reply. Great Generator by the way ....
