### ISSUE TITLE
More complete documentation

### ISSUE THREAD

**Issue by psotos** [diegohaz/rest#61]
Hi Diego!

Thanks for doing this amazing project. I feel that it needs more documentation and examples which show how to generate the various things. For example:
"If you choose to generate the authentication API, you can start to play with it." 

But you dont show in the docs what the commands are for generating that API.

I did watch the video, but still we need more docs on this awesome project.

**Comment by diegohaz** [comment]
Hi, @psotos. Thank you for the feedback.

Writing documentation is the hardest thing when doing open source. What I recommend is to play with the generator and try to figure out things that might be missing in docs, whether by posting issues or looking into the inner libraries (after all, this generator is just a combination of them, and each of them has its own docs).

If you figure out something that might be useful for others, I'd be very grateful if you help to improve the docs. ❤️
