### ISSUE TITLE
When Trying to Deploy I'm receiving the following error

### ISSUE THREAD

**Issue by mjmcgrath2010** [diegohaz/rest#62]
!     No default language could be detected for this app.
			HINT: This occurs when Heroku cannot detect the buildpack to use for this application automatically.
			See https://devcenter.heroku.com/articles/buildpacks
 !     Push failed

I've set the buildpack to be nodejs and it still is not working

**Comment by mjmcgrath2010** [comment]
I forgot to run git init 😃

**Comment by GamingPilot2** [comment]
i need help. where is git.ini i'm stuck with this error

**Comment by diegohaz** [comment]
@GamingPilot2 run `git init` on your terminal.

**Comment by uchedotphp** [comment]
git init didnt solve this for me, im still stuck with the error

**Comment by Oswaldgerald** [comment]
No default language could be detected for this app.
			HINT: This occurs when Heroku cannot detect the buildpack to use for this application automatically.
			See https://devcenter.heroku.com/articles/buildpacks
 !     Push failed
i get this error whenever i push files to heroku

**Comment by sushen** [comment]
I am facing the same issue my code is:
https://github.com/sushen/formalin

**Comment by arfankhan77** [comment]
same issue for me 
git init didn't help

**Comment by DanMMX** [comment]
@sushen that's not a code that was generated with this repo

cna you show us the code you're trying to push @Oswaldgerald @uchedotphp @arfankhan77  ?

**Comment by tayloraleach** [comment]
I forgot to actually COMMIT the requirements.txt file after creating it!

**Comment by Amol4891** [comment]
after getting this error and adding requirements.txt file you have commit this file again in following way.
`git commit -m "requirements.txt"`
`git init`
`git add -A`
`git push heroku master`

**Comment by Shubham-Nayak** [comment]
just git commit -m "comment" requirements.txt ...that's it

**Comment by mehsan851** [comment]
No default language could be detected for this app.
			HINT: This occurs when Heroku cannot detect the buildpack to use for this application automatically.
			See https://devcenter.heroku.com/articles/buildpacks
 !     Push failed

**Comment by Prafulkalal3301** [comment]
heroku create myapp --buildpack heroku/python

**Comment by braindotai** [comment]
According to official docs:
> Heroku automatically recognizes your app as a Python app if it includes a requirements.txt or setup.py file in its root directory.

In my case the requirements file was named as `requirement.txt` instead of `requirements.txt` (note the s at end) ... and after fixing this the deployment worked just fine 😛

**Comment by ikunalpn** [comment]
> According to official docs:
> 
> > Heroku automatically recognizes your app as a Python app if it includes a requirements.txt or setup.py file in its root directory.
> 
> In my case the requirements file was named as `requirement.txt` instead of `requirements.txt` (note the s at end) ... and after fixing this the deployment worked just fine 😛

thank you buddy. Same in my case

**Comment by AdnanPhy** [comment]
I  done the following to fix the problem for python language. Run the command 
heroku buildpacks:set heroku/python
Than i run the command.  git push heroku master.
I get another error. Using buildpack: heroku/python
remote: -----> App not compatible with buildpack:

The problem i fix by running the following command.

    pip3 freeze > requirements.txt
    heroku buildpacks:set heroku/python
    git add .; git commit -m "add requirements.txt"; git push heroku master
Here we go, it solve the problem.

**Comment by K1ngs1** [comment]
@kupan31 I'm making a discord bot, and what do you put inside the requirements.txt?

**Comment by Cyebukayire** [comment]
I had the same issue but [this article saved me:) ](https://mypyshop.herokuapp.com/)

**Comment by aarsht7** [comment]
> According to official docs:
> 
> > Heroku automatically recognizes your app as a Python app if it includes a requirements.txt or setup.py file in its root directory.
> 
> In my case the requirements file was named as `requirement.txt` instead of `requirements.txt` (note the s at end) ... and after fixing this the deployment worked just fine stuck_out_tongue

for me it was opposite, I had to put `requirements.txt` instead `requirement.txt`.

**Comment by avinash-03** [comment]
> > According to official docs:
> > > Heroku automatically recognizes your app as a Python app if it includes a requirements.txt or setup.py file in its root directory.
> > 
> > 
> > In my case the requirements file was named as `requirement.txt` instead of `requirements.txt` (note the s at end) ... and after fixing this the deployment worked just fine 😛
> 
> thank you buddy. Same in my case

thanks bro I am also facing same issue

**Comment by siadev1** [comment]
> 

probably missing composer.json file
