### ISSUE TITLE
Is there a way to limit the user to only retrieve their own data?

### ISSUE THREAD

**Issue by mjmcgrath2010** [diegohaz/rest#63]
Example:
I hit  `/venues`  passing `access_token` as a user

Expected: The data is contained to that users particular data.
Actual: The user sees the data for all users.

Thank you!

**Comment by diegohaz** [comment]
That won't happen *automagically*.

You need to make some changes on the code.

On the middleware chain (`index.js`), you need to enable the token getter:
```js
router.get('/',
  token(),
  query(),
  index)
```

On the `controller.js`, grab the user and filter the query:
```js
export const index = ({ user }, res) =>
  Venue.find({ user: user.id })
  ...
```

Of course, the venue must have an `user` field.

**Comment by mjmcgrath2010** [comment]
Thank you @diegohaz!
