### ISSUE TITLE
customized IDs or short url alias for ID

### ISSUE THREAD

**Issue by jessewriter** [diegohaz/rest#64]

**Comment by jessewriter** [comment]
The IDs are created in the mongoDB but I would like a short handle for an endpoint like /room1 instead of the long generated ID.  Is this possible already or do I need to write some adaptive code?

**Comment by diegohaz** [comment]
Hey, @jessewriter 

You will need to write some code.

You can do that whether by changing the default ID type (using something like https://github.com/jjwchoy/mongoose-shortid) or querying for fields other than the actual ID on the controller:

```js
export const show = ({ params }, res) =>
  Room.find({ otherField: params.id })
  ...
```

**Comment by jessewriter** [comment]
nevermind i think the issue was I was working on a branch.  sorry i'm 
pretty new at git and like it but not great at it yet.
