### ISSUE TITLE
Default ip address and port not working locally

### ISSUE THREAD

**Issue by richbrill** [diegohaz/rest#66]
Nice generator!

I have an issue however when using the default

`ip: process.env.IP || '0.0.0.0',`

in src/config.js

After doing `npm run dev` the server is unresponsive, even though it says 'Express listening...' on the command line.

Changing the ip to 127.0.0.1 fixes it.

Not sure if this is an issue with my local machine or not?

**Comment by diegohaz** [comment]
Are you using Windows? Which version? It seems to be something related to Windows.

**Comment by richbrill** [comment]
Windows 10 Home edition.

**Comment by lbilde** [comment]
On windows change ip from 0.0.0.0 to localhost or 127.0.0.1 in config.js file then it works

**Comment by richbrill** [comment]
@lbilde This is what I did but wondering if a PR should be made for it @diegohaz ?

**Comment by diegohaz** [comment]
@richbrill Yes, please. We can just use `host` (instead of `ip`) and `localhost` as the value.
