### ISSUE TITLE
[Question] What this line of code mean?

### ISSUE THREAD

**Issue by chemitaxis** [diegohaz/rest#68]
Hi Diego, one question... I am trying to understand all the project, but I have a question with that:

`import { schema } from './model';
export User, { schema } from './model';`

What does it do?

Why are you exporting and not importing the User and the Schema? I'm working with my linter and it detects as "Unexpected token".

Thanks.

**Comment by diegohaz** [comment]
That exports the model and the schema for other APIs to access them. For example, the `article` API may want to access the `user` schema, so it can just `import { schema } from '../user'` or `import { User } from '../user'` for the model.

I recommend you to use the `.eslintrc` for linting (whether with a plugin or by running `npm run lint`)

**Comment by chemitaxis** [comment]
I'm talking about the export, I know perfectly how works the import ;)
