### ISSUE TITLE
Shouldn't the access token be located in a header?

### ISSUE THREAD

**Issue by alvimm** [diegohaz/rest#69]
I saw that the generator is using the access token of the API's in the body of the request or in url query.

Usually, I see it in API's request headers. Is there a reason for using it this way? I don't know if it's a recommendation about REST or anything.

**Comment by swapnilaryan** [comment]
Well don't know quite deep into it. But there are some security reasons for which we store session, access tokens in headers and not in request body. 

It's not strictly defined, but as a rule of thumb and best practices we should use it. I am pretty sure other geeks will dive more deep into this and answer.

**Comment by alvimm** [comment]
Yeah. After some research I deduced what you just said. It looks like when the token is used once or it's kinda public, there's no problem using it in request query or body. One of the main problems of using it in queries (when it's not a one use token or public) is because it will be registered in logs.

But after studying this repo's code, I could see in `src/services/passport/index.js` that it's extracting the access token both from headers or query/body:

```
passport.use('token', new JwtStrategy({
  secretOrKey: jwtSecret,
  jwtFromRequest: ExtractJwt.fromExtractors([
    ExtractJwt.fromUrlQueryParameter('access_token'),
    ExtractJwt.fromBodyField('access_token'),
    ExtractJwt.fromAuthHeaderWithScheme('Bearer')
  ])
```

So you can use a header like this:
`Authorization: 'Bearer ${access_token}'`

Just answering my own question, in case anyone needs. hehe :)
