### ISSUE TITLE
Modify API in the CLI

### ISSUE THREAD

**Issue by shelune** [diegohaz/rest#70]
Is it possible that I can add fields / make modifications in general to an API through the CLI?

Also when trying to override an existing API (`yo rest:api` with the same name), it doesn't override the previous import in the `src/api/index.js`

For example, there'd be 2 lines of `import expense from './expense'` in the index.js file.

**Comment by jessewriter** [comment]
Yeah I changed the model.js to have an additional field and when I run the command to update the documentation I do not see my new field (nor do I see it in a get request).  Do I have to start over from the beginning and create a new project?

**Comment by diegohaz** [comment]
For fields to be shown on GET responses, you need to return them in the `view` method (model).

To update docs, you need to update the docblocks comments on the `index.js` file.

**Comment by jessewriter** [comment]
something to note is I named one api Led_controller and one LedController and the router (index.js at api root) called both of them "ledController" in the router.use method call causing my Heroku app to crash.  Luckily the Heroku logs are very useful for debugging.
