### ISSUE TITLE
Why does social login (Google & Facebook) not require clientID/appId and clientSecret/appSecret

### ISSUE THREAD

**Issue by TerencedzLi** [diegohaz/rest#71]
I'm testing out this generator, and I wanted to use social login. I was looking through the passport services, and the facebook/ google service but nowhere do I see it taking or using a
clientID/appID or clientSecret/appSecret generated from each company's respective developer console. Is this something we need to add ourselves for it to work?

Thanks

**Comment by diegohaz** [comment]
You don't need the app secret, but it means that any facebook app can register on your server.
If you want to only accept registration from a specific app, you'll need to do something like this on the facebook service (`src/services/facebook`):
```js
import crypto from 'crypto'
import request from 'request-promise'
import { fbAppSecret } from '../../config'

const getAppSecretProof = (accessToken) =>
  crypto.createHmac('sha256', fbAppSecret).update(accessToken).digest('hex')

export const getUser = (accessToken) =>
  request({
    uri: 'https://graph.facebook.com/me',
    json: true,
    qs: {
      access_token: accessToken,
      appsecret_proof: getAppSecretProof(accessToken),
      fields: 'id, name, email'
    }
  }).then(({ id, name, email }) => ({
    service: 'facebook',
    picture: `https://graph.facebook.com/${id}/picture?type=normal`,
    id,
    name,
    email
  }))
```

**Comment by pantchox** [comment]
but how am i suppose to get user accessToken? what are the stages to do that? i am more interested in github

**Comment by amimaro** [comment]
+1
