### ISSUE TITLE
POST request got 401 Unauthorized

### ISSUE THREAD

**Issue by shelune** [diegohaz/rest#72]
I deployed my database to heroku and everything works with Postman (even with CURL like in the example).

However I fail to make it work on the actual frontend when using *axios*. Here's my code
`axios({

        method: 'post',
        baseURL: 'abcdef.herokuapp.com',
        url: '/users',
        data: {
          "access_token": "123456789",
          "email": "user97@user.com",
          "password": "123456"
        },
        headers: {
          'content-type': 'application/x-www-form-urlencoded',
        }
      }).then(data => {
        console.log(data)
      })`

When I tested things in Postman it works perfectly but I couldn't make the same thing happen with axios. I assume access_token is not where it's supposed to be but I'm not sure where else to put it. Can you help me with this or is it too specific in my case?

**Comment by vposudevsky** [comment]
hi
remove  'content-type': 'application/x-www-form-urlencoded',
it works without this header

**Comment by shelune** [comment]
Thanks for your fast reply. Got this to work now.

I think I've tried a lot of different ways without it working (I didn't have that line originally but very likely I had some extra wrong lines) that I forgot that one simple line. Closing it now.
