### ISSUE TITLE
(question): why are you using setImmediate?

### ISSUE THREAD

**Issue by cameronroe** [diegohaz/rest#73]
I noticed you've used setImmediate [here](https://github.com/diegohaz/rest/blob/master/generators/app/templates/src/app.js#L12) but I'm not sure why that is. 

Could you please describe why you've chosen to do this? Thanks.

**Comment by maustand** [comment]
Hi

Proably it is a small strick where he is looking that server begins to listen after all the declarations because of setImmediate goes to the eventloop in javascript and it would be called after all.

Regards
