### ISSUE TITLE
Are you still maintaining this, it ROCKS!!

### ISSUE THREAD

**Issue by lbilde** [diegohaz/rest#74]
I need to know if you are still maintaining this AWESOME rest api generator :)

**Comment by diegohaz** [comment]
@lbilde Yes. Glad you like it. ;)

**Comment by diegohaz** [comment]
@lbilde I just found this series: https://www.youtube.com/watch?v=uI_g2zi2bkQ&list=PL8jcXf-CLpxpndi2RhEKp8284wNtONe7H&index=67

Is that yours?

**Comment by lbilde** [comment]
Yes it is :)

I am working on a new video series of a MEAN stack with Angular4 and I will use your REST API generator again as MEN of MEAN.
The start of the new series is here (21 vids until now, but only about angular4 for now)
https://www.youtube.com/playlist?list=PL8jcXf-CLpxp5fbpvg7MZBeKiw4ebJZOn

So keep up the good work!!! It is very useful this generator.

**Comment by diegohaz** [comment]
Hahaha! That's wonderful.

Feel free to add those links to README. Can help others.
