### ISSUE TITLE
New installation on linux fails. Missing express-generator. 

### ISSUE THREAD

**Issue by kub1x** [diegohaz/rest#75]
After fresh installation I got following error: 

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 4.4.6-gentoo
npm ERR! argv "/home/kub1x/.nvm/versions/node/v7.6.0/bin/node" "/home/kub1x/.nvm/versions/node/v7.6.0/bin/npm" "install"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
```

I don't really understand the error, but installing `express-generator` helped as stated in [this question](http://stackoverflow.com/a/42407741/336753). 

Perhaps the `express-generator` should be added to dependencies or to the installation instructions, or something else ;)

Cheers, 
Jakub

**Comment by maustand** [comment]
Hi

I am working on linux with the generator ( ubuntu 16.4 ).
I can not reproduce your error.
Could you provide us more details ?

Try to remove your node-modules and install your dependencies.. Probably you have a conflict.

Regards
