### ISSUE TITLE
Permissions/Roles.

### ISSUE THREAD

**Issue by countrdd** [diegohaz/rest#79]
Just started using this, great work.
So my question is how to allow a user to only update their information.

I.e. if they add a device to the devices table, I would only want them to be able to CRUD their own stuff only.

Dusty

**Comment by DanMMX** [comment]
on the generated project you can see under `src/api/user/controller.js` something like this:

```
export const update = ({ bodymen: { body }, params, user }, res, next) =>
  User.findById(params.id === 'me' ? user.id : params.id)
    .then(notFound(res))
    .then((result) => {
      if (!result) return null
      const isAdmin = user.role === 'admin'
      const isSelfUpdate = user.id === result.id
      if (!isSelfUpdate && !isAdmin) {
        res.status(401).json({
          valid: false,
          message: 'You can\'t change other user\'s data'
        })
        return null
      }
      return result
    })
    .then((user) => user ? Object.assign(user, body).save() : null)
    .then((user) => user ? user.view(true) : null)
    .then(success(res))
    .catch(next)
```

This makes possible only to admin or the same user to update a user. Similarly, you will need to implement something like this on your index and show controllers (using the option `? Do you want to store in a field the user who created the some-entity? (Y/n)`):

```

export const index = ({ querymen: { query, select, cursor }, user }, res, next) =>
  Devices.find({ user: user.id, ...query }, select, cursor)
    .then(devices => devices.map(device => device.view()))
    .then(success(res))
    .catch(next)

```

So you can find specifically the Devices created from the same user that is requesting the stuff.
