### ISSUE TITLE
Populated subdocuments does not have id (only _id) 

### ISSUE THREAD

**Issue by pedro-victor** [diegohaz/rest#80]
(First of all, great job with `generator-rest`!)

# Problem

`generator-rest` uses `id` instead of `_id` as the unique id of an object. 
(Which is great from the point of view of the API user)

But unfortunately this behaviour does not apply to populated subdocuments.

# How to reproduce

##### 1. Create the project and models

```bash
> yo rest
? What's the project name? Test
...
> yo rest:api
? What's the API name? parent
...
Which fields the model will have? (comma separated) child
...
> yo rest:api
? What's the API name? parent
...
Which fields the model will have? (comma separated) name
...
```

##### 2. Set `Child` as subdocument of `Parent` as `child`

*`src/api/parent/model.js`*
```js
child: {
  type: String
}
```
to
```js
child: {
  type: Schema.ObjectId,
  ref: 'Child'
}
```

##### 3. Add populate to `child` on `parent` and return this to user

*`src/api/parent/controller.js`*
```
export const index = ({ querymen: { query, select, cursor } }, res, next) =>
  Parent.find(query, select, cursor)
    .then((parents) => parents.map((parent) => parent.view()))
    .then(success(res))
    .catch(next)

```
to
```
export const index = ({ querymen: { query, select, cursor } }, res, next) =>
  Parent.find(query, select, cursor)
    .populate('child')
    .then((parents) => parents.map((parent) => parent.view()))
    .then(success(res))
    .catch(next)

```

##### 4. Insert dummy data

```bash
> mongo test-dev
>> db.children.insert({name: 'populate'});
>> db.parents.insert({child: db.child.findOne()._id});
```

##### 5. Run server

```bash
> npm run dev
```

##### 6. Test endpoint

```bash
> curl http://localhost:9000/parents
```

# Expected result

```js
[{"id":"5929fc28a0e02645276741f7","child":{"name":"populate","id":"5929fc24a0e02645276741f6"}}]
```

# Actual result

```js
[{"id":"5929fc28a0e02645276741f7","child":{"_id":"5929fc24a0e02645276741f6","name":"populate"}}]
```

**Comment by DanMMX** [comment]
Actually what I think you should do is add this options

`{
  toObject: {
  virtuals: true
  },
  toJSON: {
  virtuals: true 
  }
}`

to your Child model. So you get id as well
