### ISSUE TITLE
Facebook user access token

### ISSUE THREAD

**Issue by oelumeze** [diegohaz/rest#84]
I tried testing the API call for facebook authentication but returned 400 saying invalid OAuth credentials. So i would like to know what will be the facebook user access token field value when making this call. Thanks.
![screenshot from 2017-06-14 23-12-00](https://user-images.githubusercontent.com/11803701/27163662-1245982e-5157-11e7-9bb7-2c2fb77dfa69.png)

**Comment by SpiritwalkerJiang** [comment]
@oelumeze 
what you need to facebook access_token. Please refer to https://developers.facebook.com/docs/facebook-login/access-tokens#apptokens

Since this generator uses passportJS for auth management, you could get a better and deeper view from http://passportjs.org/docs/facebook
