### ISSUE TITLE
[Question] npm run build

### ISSUE THREAD

**Issue by SamJWeissman** [diegohaz/rest#85]
Just curious if the youtube video you've attached is no longer relevant.

There is no longer a "build" script in the package.json. Is there a new way to build a "distributable" or is this now up to the user?

Thanks!

**Comment by diegohaz** [comment]
Hi, @SamJWeissman 

It doesn't need to be built anymore. I've added a note on the video:

![image](https://user-images.githubusercontent.com/3068563/27461628-710bf8c2-5791-11e7-8c8d-7ced37628feb.png)

**Comment by SamJWeissman** [comment]
@diegohaz 

Awesome, thank you for the quick response!

The generator/your work is excellent so far.

I've done some front-end work but I'm super foreign to back-end. Is there any specific resource you'd recommend reading up on to get a better understanding of how the MASTER_KEY / JWT_SECRET work together? Just been reading some general stuff on JSON Web Tokens so far but not sure I follow where the MASTER_KEY comes in.
