### ISSUE TITLE
Inquiry

### ISSUE THREAD

**Issue by mackyking** [diegohaz/rest#91]
Can you offer tutorial, i mean one one one tutorial?

**Comment by mackyking** [comment]
i follow your video in youtube, after i completed the task command and open the atom text editor, then the terminal says atom is not recognized as internal or external command. What's the problem? do i lack something? Can you help me?

**Comment by diegohaz** [comment]
Hi, @mackyking 

You need to open the folder on your code editor. I've used Atom on the video, but you can use another one.
